config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  resources :books do
    member do
      get 'download_pdf'
    end
  end

  resources :foods

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homes#index"
  resources :homes
  resources :uploads
  resources :authors

  get 'facebook_data' ,to: 'homes#facebook_data'
  resources :books
  get 'download_csv', to: 'books#download_csv'
  get 'download_pdf', to: 'books#download_pdf'
  get 'delete_all_authors', to: 'authors#delete_all_authors'
  delete 'author_delete', to: 'authors#author_delete'
  get 'download_author_pdf', to: 'uploads#download_author_pdf'
  get 'download_author_csv', to: 'uploads#download_author_csv'

  post 'import_csv', to: 'books#import_csv'
  get 'delete_all_book', to: 'books#delete_all_book'
  get 'show_specific_language', to: 'books#show_specific_language'
  get 'chatgpt', to: 'homes#chatgpt'
  post 'process_import_csv', to: 'books#process_import_csv'
  post 'process_uploads', to: 'uploads#process_uploads'

  # resources :books do
  #   collection do
  #     post :process_import_csv
  #     get :import_csv
  #   end
  # end

  # resources :uploads, only: [:new, :create] do
  #   collection do
  #     post :process_uploads
  #   end
  # end

end

app/models/author.rb
class Author < ApplicationRecord

	# after_save :author_info,:send_mail

	# has_one_attached :image

	def self.ransackable_attributes(auth_object = nil)
    ["email", "id", "id_value", "name", "number"]
  end

  

	def author_info
		MailJob.perform_later(self)
	end

	def send_mail
		data = {user_name: self.name, age: 16, h: 'health', w: 'wealth'}
		WelcomeMailer.welcome_mail_to_user(self, 'grapes_template', data).deliver_now
	end



end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def new
		@author = Author.new
	end

	def index
		@authors = Author.all
    # @authors = @authors.order(updated_at: :asc)
	end

  def create
    Author.create(name: params[:name], number: params[:number], email: params[:email])
    redirect_to authors_path
  end

	def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(item_params)
    redirect_to authors_path
  end

  def delete_all_authors
  	Author.destroy_all
  	redirect_to authors_path
  end

  def author_delete
  	@author = Author.find(params[:id])
  	@author.destroy
  	respond_to :js
  	# respond_to do |format|
      # format.html { redirect_to ponies_url }
      # format.json { head :no_content }
      # format.js   { render :layout => false }
   	# end 
	end


  private

  def item_params
    params.require(:author).permit(:name, :number, :email)
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_edit_form.html.erb
<%= form_for(object, url: author_path(object), method: :patch) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/authors/_form.html.erb
<style>
  .field_width{
    width: 440px !important;
  }
</style>

<div class="container">
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
        <h4>Book Form</h4>
        </div>
        <div class="modal-body">
          <%= form_with url: authors_path do |f| %>
            <div class="container">
              <div class="field form-group">
                <%= f.label :"name" %><br>
                <%= f.text_field :name, placeholder:"name",class: 'field_width' %><br>
              </div>
              <div class="field form-group">
                <%= f.label :"number" %><br>
                <%= f.text_field :number, placeholder: "number", class: 'field_width' %><br>
              </div>
              <div class="field form-group">
                <%= f.label :"email" %><br>
                <%= f.text_field :email, placeholder: "email", class: 'field_width' %><br>
              </div>
              <div class="field form-group">
                <%= f.submit class: 'btn btn-primary field_width' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authors/_partial.html.erb
  <div class="modal fade" id="editModal<%=author.id%>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="editModalLabel">Edit Form</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <%= render 'edit_form', object: author %>
                        </div>
                    </div>
                </div>
            </div>

app/views/authors/author_delete.js.erb
$('.delete_author').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/authors/edit.js.erb
// edit.js.erb
$('#editModalContent').html('<%= j render "edit_form", author: @author %>');
$('#editModal').modal('show');

app/views/authors/index.html.erb
<%= render 'form' %>
<table class="table table-striped table-bordered table-hover friend_list">
  <thead class="thead-dark">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Number</th>
      <th>Email</th>
      <th>
        Action
        <%= link_to 'Back',  root_path, class: 'btn btn-success' %>
        <%= link_to 'Delete_all', delete_all_authors_path, class: 'btn btn-danger'  %>
      </th>
    </tr>
  </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr class="size">
          <td><%= author.id %></td>
          <td><%= author.number %></td>
          <td><%= author.name %></td>
          <td><%= author.email %></td>
          <td>
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editModal<%=author.id%>" aid="<%= author.id %>">
                Edit
            </button>
            <div class="modal fade" id="editModal<%=author.id%>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="editModalLabel">Edit Form</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <%= render 'edit_form', object: author %>
                        </div>
                    </div>
                </div>
            </div>
            <%= link_to 'Delete', author_delete_path(id: author.id), method: :delete, :remote => true,  :class => 'delete_author btn btn-danger' %>
            <button style="display: block; margin: 0 auto;" type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">New Author</button>
          </td>
        </tr>
      <% end%>
    </tbody>
</table>  

app/views/authors/update.js.erb
// update.js.erb
$('#editModal').modal('hide');
// Add your desired actions after update, e.g., updating item details on the page