config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  resources :books do
    member do
      get 'download_pdf'
    end
  end

  resources :foods

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homes#index"
  resources :homes
  resources :uploads
  resources :authors

  get 'facebook_data' ,to: 'homes#facebook_data'
  resources :books
  get 'download_csv', to: 'books#download_csv'
  get 'download_pdf', to: 'books#download_pdf'
  get 'delete_all_authors', to: 'authors#delete_all_authors'
  delete 'author_delete', to: 'authors#author_delete'
  get 'download_author_pdf', to: 'uploads#download_author_pdf'
  get 'download_author_csv', to: 'uploads#download_author_csv'

  post 'import_csv', to: 'books#import_csv'
  get 'delete_all_book', to: 'books#delete_all_book'
  get 'show_specific_language', to: 'books#show_specific_language'
  get 'chatgpt', to: 'homes#chatgpt'
  post 'process_import_csv', to: 'books#process_import_csv'
  post 'process_uploads', to: 'uploads#process_uploads'

  # resources :books do
  #   collection do
  #     post :process_import_csv
  #     get :import_csv
  #   end
  # end

  # resources :uploads, only: [:new, :create] do
  #   collection do
  #     post :process_uploads
  #   end
  # end

end

app/models/book.rb
class Book < ApplicationRecord
  require 'csv'
 #  self.abstract_class = true

 # belongs_to: user

 has_many_attached :media

 #
 #  validates :name, presence: true
 #
 # def hello
 #   puts 'my name is rohan'
 # end

 def method_name
   
 end
 
 def self.import(file)
   CSV.foreach(file.path, headers: true) do |row|
     Book.create! row.to_hash
   end
 end

  def display_name
    "#{id} #{language}"
  end


 def self.ransackable_attributes(auth_object = nil)
   ["author_name", "id", "id_value", "language", "name", "media"]
 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def create
		@book = Book.create(name: params[:name], language: params[:language], author_name: params[:author_name])
		redirect_to books_path
	end

	def download_csv
		require 'csv'
		data = generate_csv_data
		send_data data, filename: "Book.csv"
	end

	def delete_all_book
		Book.destroy_all
		redirect_to books_path, notice: "Deleted"
	end

	def import_csv
		Book.import(params[:file])
		redirect_to books_path, notice: "Book Data imported"
	end

	def index
		@books = params[:language].present? ? Book.where(language: params[:language]) : Book.all
		# @books = Book.paginate(page: params[:page], per_page: 5)
		# @books1 = @books.paginate(params[:page]).per(5)
	end

  def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		@book.update(book_params)
		redirect_to books_path
	end

	def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
   	respond_to do |format|
      format.html { redirect_to ponies_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
   	end
	end

	def process_import_csv
    if params[:csv_file].present?
      csv_text = params[:csv_file].read
      csv = CSV.parse(csv_text, headers: true)

      csv.each do |row|
        Book.create!(row.to_hash)
      end

      redirect_to admin_books_path, notice: "CSV file imported successfully."
    else
      redirect_to admin_books_path, alert: "No CSV file selected."
    end
  end

	def download_pdf
	 @book = Book.last
	 @books = Book.all
	 respond_to do |format|
		 format.html
		 format.pdf do
			 @pdf = render_to_string pdf: "Book #{@book.name}", template: "books/download_pdf", encoding: "UTF-8", formats: [:html]
			 send_data(@pdf, filename: "#{@book.name}.pdf", type: "application/pdf", disposition: 'attachment')
		 end
	 end
	end


	private

	def book_params
		params.require(:book).permit(:language, :name, :author_name)
	end

  def generate_csv_data
    CSV.generate do |csv|
      csv << ["Book Name", "Language", "Author Name"]
			Book.all.each do |book|
      	csv << [book.name, book.language, book.author_name]
			end
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_edit_form.html.erb
<%= form_for(object, url: book_path(object), method: :patch) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :language %>
    <%= f.text_field :language, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author_name %>
    <%= f.text_field :author_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/_form.html.erb
<div class="container">
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
        <h4>Book Form</h4>
        </div>
        <div class="modal-body">
          <%= form_with url: books_path do |f| %>
            <div class="container">
              <div class="field form-group">
                <%= f.label :"book_name" %><br>
                <%= f.text_field :name, placeholder:"book name" %><br>
              </div>
              <div class="field form-group">
                <%= f.label :"language" %><br>
                <%= f.text_field :language, placeholder: "language" %><br>
              </div>
              <div class="field form-group">
                <%= f.label :"author_name" %><br>
                <%= f.text_field :language, placeholder: "author_name" %><br>
              </div>
              <div class="field form-group">
                <%= f.submit class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/destroy.js.erb
$('.delete_book').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/books/download_pdf.html.erb
Books:-
<br><br><br>
<table class="table table-striped table-bordered table-hover friend_list">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Book Name</th>
            <th>Language</th>
            <th>Author Name</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
            <tr class="size">
                <td><%= book.id %></td>
                <td><%= book.name %></td>
                <td><%= book.language %></td>
                <td><%= book.author_name %></td>
            </tr>
        <% end%>
    </tbody>
</table> 

app/views/books/index.html.erb
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
            * {
                box-sizing: border-box;
            }
            body {
                margin: 0;
                font-family: Arial, Helvetica, sans-serif;
            }
            .header {
                overflow: hidden;
                background-color: #f1f1f1;
                padding: 20px 10px;
            }
            .header a {
                float: left;
                color: black;
                text-align: center;
                padding: 12px;
                text-decoration: none;
                font-size: 18px;
                line-height: 25px;
                border-radius: 4px;
            }
            .header a.logo {
                font-size: 25px;
                font-weight: bold;
            }
            .header a:hover {
                background-color: #ddd;
                color: black;
            }
            .header a.active {
                background-color: dodgerblue;
                color: white;
            }
            .header-right {
                float: right;
            }

            form {
                display: flex;
                flex-wrap: nowrap;
                /* flex-direction: column; */
                align-content: center;
                /* align-items: center; */
                justify-content: center;
                padding-top: 50px;
            }
            @media screen and (max-width: 500px) {
                .header a {
                    float: none;
                    display: block;
                    text-align: left;
                }
                .header-right {
                    float: none;
                }
            }
        </style>
    </head>
    <body>
      <div class="header">
        <a href="#default" class="logo">Library</a>
        <div class="header-right">
          <%= link_to 'Back', root_path, class: 'btn btn-info' %> <%= link_to "Download Book List", download_csv_path, class: 'btn btn-warning' %> <%= link_to "Delete All", delete_all_book_path, data: {confirm: 'Are you sure want to
          delete all?'}, class: 'btn btn-danger' %>
          <%= link_to 'download_pdf',  download_pdf_path(format: :pdf), class: 'btn btn-info' %>
        </div>
      </div>
    </body>
</html>
<h3 style="text-align: center;">
    Import Book data <%=form_tag import_csv_path, multipart: true do %>
    <div style="text-align: center;">
        <%=file_field_tag :file, multiple: :true %>
    </div>
    <%=submit_tag "Import CSV", class: "btn btn-warning" %> <%end%>
</h3>

<%= form_with url: books_path, method: :get,remote: true, id: 'abc' do |f| %>
  <div class="field">
    <%= f.label :language %>
    <% @languages = Book.pluck(:language).uniq %>
    <%= f.select :language, options_for_select(@languages), { prompt: "Select a Language" }, { onchange: "this.form.submit();" } %>
  </div>
<% end %>

<%= render 'form' %>
<br />
<% if Book.exists? %>
<table class="table table-striped table-bordered table-hover friend_list">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Language</th>
            <th>Author Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr class="size">
            <td><%= book.id %></td>
            <td><%= book.name %></td>
            <td><%= book.language %></td>
            <td><%= book.author_name %></td>
            <td>
                <button style="display: block; margin: 0 auto;" type="button" class="btn btn-info btn-lg" id="edit_book" data-toggle="modal" data-target="#myModal">New Book</button>
            </td>
            <td>
                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editModal<%=book.id%>" aid="<%= book.id %>">
                    Edit
                </button>
                <div class="modal fade" id="editModal<%=book.id%>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editModalLabel">Edit Form</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <%= render 'edit_form', object: book %>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
            <td><%= link_to 'Delete', book, method: :delete, :remote => true, data: {confirm: 'are you sure ?'}, :class => 'delete_book btn btn-danger' %></td>
        </tr>
        <% end%>
    </tbody>
</table>
<%end%>

<%#= will_paginate @books1 %>
<%#= page_entries_info @books1 %>

<%= link_to 'alert', id: 'alert_id' %>



<p id="p1">jQuery is fun!!</p>


<script>
$(document).ready(function(){
  $("#btn1").click(function(){
    $("#test1").text("Hello world!");
  });
  $("#btn2").click(function(){
    $("#test2").html("<b>Hello world!</b>");
  });
  $("#btn4").click(function(){
    $("#test3").val("Dolly Duck");
  });
});
</script>
</head>
<body>

<p id="test1">This is a paragraph.</p>
<p id="test2">This is another paragraph.</p>

<p>Input field: <input type="text" id="test3" value="Mickey Mouse"></p>

<button id="btn1">Set Text</button>
<button id="btn2">Set HTML</button>
<button id="btn3">Set Value</button>

<%= button_to 'set set', id: 'btn4' %>
<%= link_to 'Set Wet', data: {confirm: 'are you sure ?'}, :class => 'delete_book btn btn-danger' %>


<script type="text/javascript">
// $(document).ready( function(){
  // $('select').on("change",function(e){
    // $('#abc').submit();
  // });
// });

$(document).ready(function(){
  $("alert_id").click(function(){
    $("#p1").css("color", "red").slideUp(2000).slideDown(2000);
  });
});
</script>

app/views/books/index.js.erb
index.js.erb