config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  resources :books do
    member do
      get 'download_pdf'
    end
  end

  resources :foods

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homes#index"
  resources :homes
  resources :uploads
  resources :authors

  get 'facebook_data' ,to: 'homes#facebook_data'
  resources :books
  get 'download_csv', to: 'books#download_csv'
  get 'download_pdf', to: 'books#download_pdf'
  get 'delete_all_authors', to: 'authors#delete_all_authors'
  delete 'author_delete', to: 'authors#author_delete'
  get 'download_author_pdf', to: 'uploads#download_author_pdf'
  get 'download_author_csv', to: 'uploads#download_author_csv'

  post 'import_csv', to: 'books#import_csv'
  get 'delete_all_book', to: 'books#delete_all_book'
  get 'show_specific_language', to: 'books#show_specific_language'
  get 'chatgpt', to: 'homes#chatgpt'
  post 'process_import_csv', to: 'books#process_import_csv'
  post 'process_uploads', to: 'uploads#process_uploads'

  # resources :books do
  #   collection do
  #     post :process_import_csv
  #     get :import_csv
  #   end
  # end

  # resources :uploads, only: [:new, :create] do
  #   collection do
  #     post :process_uploads
  #   end
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @authors = Author.all
  end

  def facebook_data
    @graph = Koala::Facebook::API.new
    @profile = @graph.get_object("me")
    require "uri"
    require "net/http"
    url = URI("https://graph.facebook.com/v18.0/3725650561095985/posts?access_token=#{@graph.access_token}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Get.new(url)
    response = https.request(request)
    @messages =  JSON.parse(response.body)["data"]
  end

  def chatgpt
    if params[:search]
      @response = ChatgptService.new(params[:search]).call
    end
	end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<div class="container">
  <h2 style="text-align: center;" >Form</h2>
  <button style="text-align: center;" type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">New</button>
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
        <h4>Book Form</h4>
        </div>
        <div class="modal-body">
          <%= form_with url: books_path do |f| %>
            <div class="container">
              <div class="field form-group">
                <%= f.label :"name" %><br>
                <%= f.text_field :name, placeholder:"book name" %><br>
              </div>
              <div class="field form-group">
                <%= f.label :"language" %><br>
                <%= f.text_field :language, placeholder: "language" %><br>
              </div>
              <div class="field form-group">
                <%= f.submit class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/edit.html.erb
<%= render 'form' %>

app/views/homes/facebook_data.html.erb
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td><%= @profile["id"] %></td>
        <td><%= @profile["name"] %></td>
      </tr>
    </tbody>
</table>

<table class="table table-striped table-bordered table-hover friend_list">
    <thead class="thead-dark">
        <tr>
            <th>id</th>
            <th>message</th>
            <th>created time</th>

        </tr>
    </thead>
    <tbody>
        <% @messages.each do |mess| %>
            <tr class="size">
                <td><%= mess['id']%> </td>
                <td><%= mess['message'] %></td>
                <td><%= mess['created_time'] %></td>
            </tr>
        <% end%>
    </tbody>
</table>  



<h1 style="text-align: center;">
    <br><%= link_to "Back", root_path, class: 'btn btn-secondary' %>
</h1>

app/views/homes/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th><%= link_to "Facebook Posts", facebook_data_path, class: 'btn btn-primary' %></th>
      <th><%= link_to "Instagram Posts", facebook_data_path, class: 'btn btn-danger' %></th>
      <th><%= link_to "Books", books_path, class: 'btn btn-info' %></th>
    </tr>
  </thead>
</table>
<body>
<h5 style="text-align:center;" >
  <%= link_to "Multiple CSV Upload", new_upload_path, class: 'btn btn-info' %>  
  <%= link_to 'download_author_pdf',  download_author_pdf_path(format: :pdf), class: 'btn btn-warning' %>
  <%= link_to 'download_author_csv',  download_author_csv_path(format: :pdf), class: 'btn btn-dark' %>
  <%= link_to 'Go for Authors', authors_path, method: :get, class: 'btn btn-warning' %>
</h5>


<%= form_with url: chatgpt_path, method: :get do |f| %>
  <%= f.label :"search" %><br>
  <%= f.text_field :search, placeholder:"search info" %><br><br>
  <%= f.submit 'search', class: 'btn btn-primary' %>
<% end %>

<!-- 
<br><br><br>
<table class="table table-striped table-bordered table-hover friend_list">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Number</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @authors.each do |author| %>
            <tr class="size">
                <td><%= author.id %></td>
                <td><%= author.number %></td>
                <td><%= author.name %></td>
                <td><%= author.email %></td>
                <td><%= link_to "Edit", edit_author_path(author), remote: true, data: { toggle: "modal", target: "#editModal" } %></td>
            </tr>
        <% end%>
    </tbody>
</table>   -->